---
title: "NYCABs"
author: "Jo"
date: "16 de octubre de 2017"
output: html_document
  html_document: 
    toc: true
    toc_depth: 3
    number_sections: true
---
# Nom Document

Objectius ...

## R Markdown

Vull posar **negreta**, o emfasi en *cursiva*.

Llistes:
  - Item 1
  - Item 2
  
Create lists: Unordered * and +     or   ordered   1. 2.  

  1. Item 1
  2. Item 2
    + Item 2a
    + Item 2b

```{r}
# Aixó és un comentari
#load()

```

## Load Some useful functions

```{r, echo=FALSE}

man.dist.manual <- function(p1Lat, p1Lon, p2Lat, p2Lon) {
  #return(abs(pointDistance(c(p1$lon, p1$lat), c(p1$lon, p2$lat), longlat=TRUE)) + abs(pointDistance(c(p2$lon, p1$lat), c(p2$lon, p2$lat), longlat=TRUE)))
  R = 6371
  lat1 = degrees.to.radians(p1Lat)
  lon1 = degrees.to.radians(p1Lon)
  lat2 = degrees.to.radians(p2Lat)
  lon2 = degrees.to.radians(p2Lon)
  A_lat = lat2 - lat1
  A_lon = lon2 - lon1
  a = sin(A_lat/2)^2
  c = 2 * atan2(sqrt(a), sqrt(1-a))
  dist_lat = R * c
  a = sin(A_lon/2)^2
  c = 2 * atan2(sqrt(a), sqrt(1-a))
  dist_lon = R * c
  abs(dist_lat) + abs(dist_lon)
  return(abs(dist_lat) + abs(dist_lon))
}

dfProva <- dfD4 
vectorDistances <- man.dist.manual(dfProva$Pickup_latitude, dfProva$Pickup_longitude, dfProva$Dropoff_latitude, dfProva$Dropoff_longitude)

dfD4$tlenkm <- vectorDistances



degrees.to.radians<-function(value) {
  return(value*0.0174532925)
}

# Some useful functions
calcQ <- function(x) {
  s.x <- summary(x)
  iqr<-s.x[5]-s.x[2]
  list(souti=s.x[2]-3*iqr, mouti=s.x[2]-1.5*iqr, min=s.x[1], q1=s.x[2], q2=s.x[3], 
       q3=s.x[5], max=s.x[6], mouts=s.x[5]+1.5*iqr, souts=s.x[5]+3*iqr ) }

countNA <- function(x) {
  mis_x <- NULL
  for (j in 1:ncol(x)) {mis_x[j] <- sum(is.na(x[,j])) }
  mis_x <- as.data.frame(mis_x)
  rownames(mis_x) <- names(x)
  mis_i <- rep(0,nrow(x))
  for (j in 1:ncol(x)) {mis_i <- mis_i + as.numeric(is.na(x[,j])) }
  list(mis_col=mis_x,mis_ind=mis_i) }

countX <- function(x,X) {
  n_x <- NULL
  for (j in 1:ncol(x)) {n_x[j] <- sum(x[,j]==X) }
  n_x <- as.data.frame(n_x)
  rownames(n_x) <- names(x)
  nx_i <- rep(0,nrow(x))
  for (j in 1:ncol(x)) {nx_i <- nx_i + as.numeric(x[,j]==X) }
  list(nx_col=n_x,nx_ind=nx_i) }
```

# EDA

```{r}
names(df)
boxplot(df$Total_amount)
#library(car)
Boxplot(df$Total_amount,id.n=20,col="green",main="Boxplot Target Numeric")
summary(df$Total_amount)
rr<-calcQ(df$Total_amount)
abline(h=rr$souts,col="red",lwd=2)
```

